name: Publish to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Rename readme to index
        run: mv README.md index.md

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.1
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: true
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages